### ISSUE TITLE
Recaptcha doesn't load, resulting in a unusable site

### ISSUE THREAD

**Issue by Noobfortress** [Dinnerbone/mcstatus#73] opened 2019-11-06 11:47 UTC
The site tries to load recaptcha from (https://www.google.com/recaptcha/api/js/recaptcha_ajax.js), which doesn't work due to a mime type mismatch. Results in the tool not loading at all.

Tested in firefox (v70.0.1) and edge (v44.17763.771.0), both givve the same errors

Errors in firefox:
`The resource from “https://www.google.com/recaptcha/api/js/recaptcha_ajax.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

`Loading failed for the <script> with source “https://www.google.com/recaptcha/api/js/recaptcha_ajax.js”.`

`ReferenceError: Recaptcha is not defined`

Errors in edge:
`Script from https://www.google.com/recaptcha/api/js/recaptcha_ajax.js was blocked due to mime type mismatch`

`'Recaptcha' is not defined`

**Comment by MarkL4YG** [comment] 2019-11-06 14:42
Hi @Noobfortress 👋 ,
this repository is community-maintained since a while now and we cannot provide support for Dinnerbone's personal site.  
This is a duplicate of #68 and #67 .

**Comment by kevinkjt2000** [comment] 2019-11-10 01:11
All I can say is, try to reach out to @Dinnerbone through twitter or via some other means.  His website code is not stored in this repo.

**Closed by kevinkjt2000** 2019-11-10 01:11 UTC
Labels: Invalid
