### ISSUE TITLE
timeout when connect to spigot

### ISSUE THREAD

**Issue by theundefined** [Dinnerbone/mcstatus#77] opened 2020-03-19 00:40 UTC
```
(mc) undefine@uml:~/programowanie/mc$ mcstatus mc.aramin.net status
version: vSpigot 1.8.8 (protocol 47)
description: "§f§lMC§6§lARAMIN§f§l.NET §a§lNAJLEPSZE EASEHC "
players: 0/2020 No players online
(mc) undefine@uml:~/programowanie/mc$ mcstatus mc.aramin.net query
Traceback (most recent call last):
  File "/home/undefine/programowanie/mc/bin/mcstatus", line 8, in <module>
    sys.exit(cli())
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/mcstatus/scripts/mcstatus.py", line 113, in query
    response = server.query()
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/mcstatus/server.py", line 82, in query
    raise exception
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/mcstatus/server.py", line 77, in query
    querier.handshake()
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/mcstatus/querier.py", line 32, in handshake
    packet = self._read_packet()
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/mcstatus/querier.py", line 25, in _read_packet
    packet.receive(self.connection.read(self.connection.remaining()))
  File "/home/undefine/programowanie/mc/lib/python3.7/site-packages/mcstatus/protocol/connection.py", line 178, in read
    result.extend(self.socket.recvfrom(self.remaining())[0])
socket.timeout: timed out

```

**Comment by kevinkjt2000** [comment] 2020-03-19 04:24
Duplicate of #72 
Please check that the query port is open on any firewalls

**Closed by kevinkjt2000** 2020-03-19 04:24 UTC
