### ISSUE TITLE
UDPAsyncSocketConnection cannot write anything special itself

### ISSUE THREAD

**Issue by CoolCat467** [Dinnerbone/mcstatus#214] opened 2022-02-14 00:02 UTC
`UDPAsyncSocketConnection`'s definition of `write` is an asynchronous function, while it's base class `AsyncReadConnection`'s base class `Connection` expects `write` to be a synchronous function for all of the special write functions like `write_utf`. This appears to have never been detected because everything that uses `UDPAsyncSocketConnection` manually writes everything.

**Comment by kevinkjt2000** [comment] 2022-02-14 03:08
Duplicate of #210?

**Comment by CoolCat467** [comment] 2022-02-21 18:49
Kind of but not really. It's the same type of problem I guess you could say. Number 210's seems to be mostly focused on AsyncServerQuerier. This issue is about UDPAsyncSocketConnection. But both issues are about base classes thinking a function the subclass implements being a different type than they are, like synchronous instead of asynchronous.

**Comment by ItsDrike** [comment] 2022-02-21 18:51
Hi @CoolCat467, the repo has been moved to [py-mine/mcstatus](https://github.com/py-mine/mcstatus) (as can be seen from the README), please comment there, the issues have been migrated too so you can just find the [corresponding one](https://github.com/py-mine/mcstatus/issues/214).

**Closed** 2022-02-21 22:35 UTC
