### ISSUE TITLE
Query consistently times out

### ISSUE THREAD

**Issue by ThePsionic** [Dinnerbone/mcstatus#64] opened 2018-09-02 14:00 UTC
Tested on multiple servers both on 1.12 and 1.13, using the command line tool after installing it through `pip`.
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\mcstatus-script.py", line 11, in <module>
    load_entry_point('mcstatus==2.2', 'console_scripts', 'mcstatus')()
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\mcstatus\scripts\mcstatus.py", line 79, in query
    response = server.query()
  File "c:\python27\lib\site-packages\mcstatus\server.py", line 82, in query
    raise exception
socket.timeout: timed out
```
The `ping` and `status` protocols do work as expected, and I am able to join both servers in-game.

**Comment by MarkL4YG** [comment] 2018-09-04 14:18
This repository is heavily outdated. Your issue most probably only serves as a mention of what issues this currently has but don't expect it to be fixed at some point.  
You may want to fork this repo and fix this on your own.

**Comment by netmonger** [comment] 2018-10-05 15:34
Double check that the server has `enable-query=true` in the `server.properties`.  That was my problem.  Once set to `true` I was getting results for a query.

**Comment by kevinkjt2000** [comment] 2019-05-08 00:45
@ThePsionic Are you still experiencing this issue after netmonger's suggestion?  I think it is also possible that the query port you were contacting was not open in some firewall configuration.  Feel free to close this issue if your problem was resolved already.

**Comment by kevinkjt2000** [comment] 2019-05-08 00:59
Actually, closing this as a duplicate of #60

**Closed by kevinkjt2000** 2019-05-08 00:59 UTC
Labels: Question
